### PR TITLE
[FIX] A workaround to frozendict in new api for onchanges

### PR DESCRIPTION
**Pull request by hbto**

### CODE REVIEW

**Comment by oscarolar** [comment]
I Tried .copy with new API here is an example https://github.com/AlceConsorcio/odoo_cost_engineering/blob/master/mrp_bom_multilevel/wizard/replicate_boms.py#L75
There is also a method in the new API called .with_context()

**Comment by alcedev** [comment]
Perhaps something like this may come in handy: https://github.com/AlceConsorcio/odoo_cost_engineering/blob/master/mrp_bom_multilevel/product.py#L157

**Comment by hbto** [comment]
@nhomar I have not tried copy, but I thought about it, my rationale is that if we copy we will endup with and instance of the same frozendict, because frozencopy implements all the methods exception made 
to those ones that modify the dict.

@nhomar Your comment is quite valid.

@alcedev I can see that you implemented copy, but I cannot see that you mutated the ctx afterwards.

Can you provide an example where you implement mutation after copying a frozendict.

Best Regards.

**Comment by hbto** [comment]
@josemoralesp  I think that your proposal
is better than copy.

 localcontext = dict(context) without iterations

You have implemented copy, I repeat, but you have not implemented mutation on the resulting copy.

Best Regards.

**Comment by oscarolar** [comment]
the @alcedev  method actually mutates the context....

**Comment by moylop260** [comment]
FYI you can use with context like this:
[wc](https://github.com/Vauxoo/stock-logistics-workflow/blob/8.0/product_unique_serial/tests/test_for_unicity.py#L87-L88)

**Comment by josemoralesp** [comment]
someone :+1:

**Comment by alcedev** [comment]
Indeed, not in the original one per se. Nevertheless, as @moylop260 said, you could call something with the new one [Like this](https://github.com/AlceConsorcio/odoo_cost_engineering/blob/master/mrp_bom_multilevel/product.py#L197-L200). Best late than never, they say.

Cheers

**Comment by hbto** [comment]
@alcedev  

```
    for field in fields_lst:
        if field.selectable:
            try:
                model_obj = self.env[field.model]
            except:
```

what does this piece of code refers to?

Can you make you point clear? please.

Regards.

**Comment by alcedev** [comment]
It is actually this code:
_self = self.with_context(active_test=False, create_product_variant=True)
...
_self.env['product.product'].create({'product_tmpl_id': tmpl_id.id, 'attribute_value_ids': [(6, False, values_ids)]})

Seems like the previous link now refers to another piece of code.

Just my 2 cents, cheers.

**Pull request merged**
