### PR TITLE
[ADD][ifrs_permission_user_audit] TASK#3157, ISSUE#558 

### PR DESCRIPTION
**Pull request by hugho-ad**
"Grand read permissios to Auditor (Read-Only) group"
            "over ifrs_report model",

### CODE REVIEW

**Comment by hbto** [comment]
@hugho-ad & @nhomar Why don't you propose this module as one additional group inside ifrs_report itself,

Otherwise create this module as a new module inside private repo in customer's private repo.

I do not envision yet a new module other than those ones already available in this repo.

Best Regards.

**Comment by nhomar** [comment]
@hbto 

I am agreed with this approach (I asked for it).
This team is necesary on 3 customers at same time and copy and paste such ACL is not a good approach.

Can you extend a little why do you this it is not correct on this repository, in order to understand if we move it or not?

I personally even think that offer a readonly set of elements is a good approach on this repository (our main report repository by far now).

Regards.

**Comment by hbto** [comment]
@nhomar I think did not explain myself well.

I proposed two options:

a) Instead of creating a new module, integrated the groups and ACL into the ifrs_report module itself

b) create the acl module as one in the customers repo

Given that three different customers need the same feature then I lean toward integrating the 
ACL as part of ifrs_report security section instead of creating a new module of this repo.

New module will come but they will be to add new features

As security is a feature by itself to the module then it should be integrated into the module
and not an option, that is, not a separated module.

I do agree on creating new module but for major changes or features like XBRL, 
this feature will be a major change onto ifrs and will deserve a new module by itself.

Best Regards.

**Comment by hugho-ad** [comment]
@hbto ,
An apology, I am a beginner at this, option a) means that only menus_acces and ALC will move to the module ifrs, if so, it seems a good choice.

**Comment by nhomar** [comment]
@hbto @hugo-ad

I am agreed now with @hbto and with you.

excellent, execute please.

On Mon, Apr 13, 2015 at 11:44 AM, Hugo notifications@github.com wrote:

> @hbto https://github.com/hbto ,
> An apology, I am a beginner at this, option a) means that only menus_acces
> and ALC will move to the module ifrs, if so, it seems a good choice.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Vauxoo/odoo-ifrs/pull/31#issuecomment-92421797.

## 

Nhomar Hernandez
CEO Vauxoo.
Site: http://vauxoo.com
Twitter: @nhomar
Blog: http://geronimo.com.ve
LPUser: http://launchpad.net/~nhomar
Odoo Gold Partner

**Comment by hugho-ad** [comment]
@nhomar ,
if all is ok, I'm going to make the one more pr with the suggested changes

**Comment by hugho-ad** [comment]
@hbto , @nhomar 
here is the pr 
https://github.com/Vauxoo/odoo-ifrs/pull/32

**Pull request closed without merging**
